name = "PlasmaWaves"
uuid = "12efb907-3f94-4823-94fe-a707db5a5005"
version = "0.1.1"
authors = ["Zijin Zhang <zijin@ucla.edu>"]

[workspace]
projects = ["docs", "test"]

[deps]
Bumper = "8ce10254-0962-460f-a3d8-1f77fea1446e"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
SpaceDataModel = "0b37b92c-f0c5-4a52-bd5c-390dec20857c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[weakdeps]
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"

[extensions]
PlasmaWavesDimensionalDataExt = "DimensionalData"

[compat]
Bumper = "0.7"
DimensionalData = "0.29"
FFTW = "1"
LinearAlgebra = "1"
PrecompileTools = "1"
SpaceDataModel = "0.2.2"
StaticArrays = "1.9"
Tullio = "0.3"
julia = "1.10"
